// <auto-generated />
using System;
using InsureZen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsureZen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422235149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsureZen.Models.Entities.Claim", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("text");

                    b.Property<string>("CheckerDecision")
                        .HasColumnType("text");

                    b.Property<string>("CheckerFeedback")
                        .HasColumnType("text");

                    b.Property<string>("CheckerId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CheckerReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalClaimReference")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ForwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForwardedTo")
                        .HasColumnType("text");

                    b.Property<string>("InsuranceCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MakerFeedback")
                        .HasColumnType("text");

                    b.Property<string>("MakerId")
                        .HasColumnType("text");

                    b.Property<string>("MakerRecommendation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MakerReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClaimId");

                    b.HasIndex("InsuranceCompany");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionDate");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsureZen.Models.Entities.Claim", b =>
                {
                    b.OwnsOne("InsureZen.Models.Entities.StandardizedData", "StandardizedData", b1 =>
                        {
                            b1.Property<Guid>("ClaimId");

                            b1.Property<float?>("ClaimAmount");

                            b1.PrimitiveCollection<string>("DiagnosisCodes")
                                .IsRequired();

                            b1.Property<float?>("InsuranceCoveredAmount");

                            b1.Property<DateOnly?>("PatientDateOfBirth");

                            b1.Property<string>("PatientName");

                            b1.Property<float?>("PatientResponsibility");

                            b1.Property<string>("PolicyNumber");

                            b1.PrimitiveCollection<string>("ProcedureCodes")
                                .IsRequired();

                            b1.Property<string>("ProviderName");

                            b1.Property<DateOnly?>("ServiceDate");

                            b1.Property<float?>("TotalBilledAmount");

                            b1.HasKey("ClaimId");

                            b1.ToTable("Claims");

                            b1.ToJson("StandardizedData");

                            b1.WithOwner()
                                .HasForeignKey("ClaimId");
                        });

                    b.Navigation("StandardizedData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
